import { normalizeStaticValue } from 'platejs';

/**
 * The canonical, single-document workspace. System Nodes are ordinary Plate
 * Nodes: hierarchy is still derived entirely from flat indent and order.
 */
export const initialDocument = normalizeStaticValue([
  {
    children: [{ text: 'Local Tana' }],
    id: 'workspace-root',
    tanaSystemNode: 'workspace',
    type: 'p',
  },
  {
    children: [{ text: '主页' }],
    id: 'home',
    indent: 1,
    tanaSystemNode: 'home',
    type: 'p',
  },
  {
    children: [{ text: 'Plate 提供编辑器能力，Local Tana 只补充语义。' }],
    id: 'node-principle',
    indent: 2,
    type: 'p',
  },
  {
    children: [{ text: 'Plate 文档是唯一真相源。' }],
    id: 'node-document-source',
    indent: 3,
    type: 'p',
  },
  {
    children: [
      { text: '示例 ' },
      { children: [{ text: '' }], key: 'supertag-project', type: 'tana_supertag' },
    ],
    id: 'node-project-example',
    indent: 2,
    tanaSupertagIds: ['supertag-project'],
    type: 'p',
  },
  {
    children: [{ text: '' }],
    id: 'field-node-project-summary',
    indent: 3,
    tanaFieldId: 'field-summary',
    type: 'p',
  },
  {
    children: [{ text: '' }],
    id: 'field-value-project-summary',
    indent: 4,
    tanaFieldValueType: 'plain',
    type: 'p',
  },
  {
    children: [{ text: '' }],
    id: 'field-node-project-estimate',
    indent: 3,
    tanaFieldId: 'field-estimate',
    type: 'p',
  },
  {
    children: [{ text: '' }],
    id: 'field-value-project-estimate',
    indent: 4,
    tanaFieldValueType: 'number',
    type: 'p',
  },
  {
    children: [{ text: '' }],
    id: 'field-node-project-active',
    indent: 3,
    tanaFieldId: 'field-active',
    type: 'p',
  },
  {
    children: [{ text: '' }],
    id: 'field-value-project-active',
    indent: 4,
    tanaFieldValueType: 'checkbox',
    type: 'p',
  },
  {
    children: [{ text: '' }],
    id: 'field-node-project-due',
    indent: 3,
    tanaFieldId: 'field-due',
    type: 'p',
  },
  {
    children: [{ text: '' }],
    id: 'field-value-project-due',
    indent: 4,
    tanaFieldValueType: 'date',
    type: 'p',
  },
  {
    children: [{ text: '' }],
    id: 'field-node-project-status',
    indent: 3,
    tanaFieldId: 'field-status',
    type: 'p',
  },
  {
    children: [{ text: '' }],
    id: 'field-value-project-status',
    indent: 4,
    tanaFieldValueType: 'options',
    type: 'p',
  },
  {
    children: [{ text: '' }],
    id: 'field-node-project-owner',
    indent: 3,
    tanaFieldId: 'field-owner',
    type: 'p',
  },
  {
    children: [{ text: '' }],
    id: 'field-value-project-owner',
    indent: 4,
    tanaFieldValueType: 'from-supertag',
    type: 'p',
  },
  {
    children: [{ text: 'SQLite 在本地持久化文档。' }],
    id: 'node-local-persistence',
    indent: 2,
    type: 'p',
  },
  {
    children: [{ text: '每日笔记' }],
    id: 'daily-notes',
    indent: 1,
    tanaSystemNode: 'daily-notes',
    type: 'p',
  },
  {
    children: [{ text: 'Schema' }],
    id: 'schema',
    indent: 1,
    tanaSystemNode: 'schema',
    type: 'p',
  },
  {
    children: [{ text: '项目' }],
    id: 'supertag-project',
    indent: 2,
    tanaSupertagDefinition: {},
    type: 'p',
  },
  {
    children: [{ text: '' }],
    id: 'template-field-summary',
    indent: 3,
    tanaFieldId: 'field-summary',
    type: 'p',
  },
  {
    children: [{ text: '' }],
    id: 'template-value-summary',
    indent: 4,
    tanaFieldValueType: 'plain',
    type: 'p',
  },
  {
    children: [{ text: '' }],
    id: 'template-field-estimate',
    indent: 3,
    tanaFieldId: 'field-estimate',
    type: 'p',
  },
  {
    children: [{ text: '' }],
    id: 'template-value-estimate',
    indent: 4,
    tanaFieldValueType: 'number',
    type: 'p',
  },
  {
    children: [{ text: '' }],
    id: 'template-field-active',
    indent: 3,
    tanaFieldId: 'field-active',
    type: 'p',
  },
  {
    children: [{ text: '' }],
    id: 'template-value-active',
    indent: 4,
    tanaFieldValueType: 'checkbox',
    type: 'p',
  },
  {
    children: [{ text: '' }],
    id: 'template-field-due',
    indent: 3,
    tanaFieldId: 'field-due',
    type: 'p',
  },
  {
    children: [{ text: '' }],
    id: 'template-value-due',
    indent: 4,
    tanaFieldValueType: 'date',
    type: 'p',
  },
  {
    children: [{ text: '' }],
    id: 'template-field-status',
    indent: 3,
    tanaFieldId: 'field-status',
    type: 'p',
  },
  {
    children: [{ text: '' }],
    id: 'template-value-status',
    indent: 4,
    tanaFieldValueType: 'options',
    type: 'p',
  },
  {
    children: [{ text: '' }],
    id: 'template-field-owner',
    indent: 3,
    tanaFieldId: 'field-owner',
    type: 'p',
  },
  {
    children: [{ text: '' }],
    id: 'template-value-owner',
    indent: 4,
    tanaFieldValueType: 'from-supertag',
    type: 'p',
  },
  {
    children: [{ text: '摘要' }],
    id: 'field-summary',
    indent: 2,
    tanaFieldDefinition: { type: 'plain' },
    type: 'p',
  },
  {
    children: [{ text: '预估' }],
    id: 'field-estimate',
    indent: 2,
    tanaFieldDefinition: { type: 'number' },
    type: 'p',
  },
  {
    children: [{ text: '进行中' }],
    id: 'field-active',
    indent: 2,
    tanaFieldDefinition: { type: 'checkbox' },
    type: 'p',
  },
  {
    children: [{ text: '截止日期' }],
    id: 'field-due',
    indent: 2,
    tanaFieldDefinition: { type: 'date' },
    type: 'p',
  },
  {
    children: [{ text: '状态' }],
    id: 'field-status',
    indent: 2,
    tanaFieldDefinition: { type: 'options' },
    type: 'p',
  },
  { children: [{ text: '计划中' }], id: 'option-planned', indent: 3, type: 'p' },
  { children: [{ text: '进行中' }], id: 'option-active', indent: 3, type: 'p' },
  { children: [{ text: '已完成' }], id: 'option-completed', indent: 3, type: 'p' },
  {
    children: [{ text: '负责人' }],
    id: 'field-owner',
    indent: 2,
    tanaFieldDefinition: { sourceSupertagId: 'supertag-project', type: 'from-supertag' },
    type: 'p',
  },
  {
    children: [{ text: '资料库' }],
    id: 'library',
    indent: 1,
    tanaSystemNode: 'library',
    type: 'p',
  },
  {
    children: [{ text: '全部项目' }],
    id: 'view-projects',
    indent: 2,
    tanaSearchDefinition: { clauses: [{ kind: 'has-supertag', supertagId: 'supertag-project' }] },
    tanaViewDefinition: { type: 'outline' },
    type: 'p',
  },
  {
    children: [{ text: '设置' }],
    id: 'settings',
    indent: 1,
    tanaSystemNode: 'settings',
    type: 'p',
  },
  {
    children: [{ text: '回收站' }],
    id: 'trash',
    indent: 1,
    tanaSystemNode: 'trash',
    type: 'p',
  },
]);
