import { normalizeStaticValue } from 'platejs';

/** A structurally complete Field-as-Node document. */
export const initialDocument = normalizeStaticValue([
  { id: 'workspace-root', children: [{ text: 'Local Tana' }], type: 'p' },
  {
    id: 'node-principle',
    children: [{ text: 'Plate 提供编辑器能力，Local Tana 只补充语义。' }],
    indent: 1,
    type: 'p',
  },
  {
    id: 'node-document-source',
    children: [{ text: 'Plate 文档是唯一真相源。' }],
    indent: 2,
    type: 'p',
  },
  { id: 'node-first-loop', children: [{ text: '第一个可用闭环' }], type: 'toggle' },
  {
    id: 'node-reference',
    children: [
      { text: '行内引用复用 Plate Mention：' },
      { children: [{ text: '' }], key: 'workspace-root', type: 'mention' },
    ],
    indent: 1,
    type: 'p',
  },
  { id: 'node-supertag', children: [{ text: '超级标签复用 Plate Combobox。' }], indent: 1, type: 'p' },
  {
    id: 'supertag-project',
    children: [{ text: '项目' }],
    indent: 2,
    tanaSupertagDefinition: {},
    type: 'p',
  },
  { id: 'template-field-summary', children: [{ text: '' }], indent: 3, tanaFieldId: 'field-summary', type: 'p' },
  { id: 'template-value-summary', children: [{ text: '' }], indent: 4, tanaFieldValueType: 'plain', type: 'p' },
  { id: 'template-field-estimate', children: [{ text: '' }], indent: 3, tanaFieldId: 'field-estimate', type: 'p' },
  { id: 'template-value-estimate', children: [{ text: '' }], indent: 4, tanaFieldValueType: 'number', type: 'p' },
  { id: 'template-field-active', children: [{ text: '' }], indent: 3, tanaFieldId: 'field-active', type: 'p' },
  { id: 'template-value-active', children: [{ text: '' }], indent: 4, tanaFieldValueType: 'checkbox', type: 'p' },
  { id: 'template-field-due', children: [{ text: '' }], indent: 3, tanaFieldId: 'field-due', type: 'p' },
  { id: 'template-value-due', children: [{ text: '' }], indent: 4, tanaFieldValueType: 'date', type: 'p' },
  { id: 'template-field-status', children: [{ text: '' }], indent: 3, tanaFieldId: 'field-status', type: 'p' },
  { id: 'template-value-status', children: [{ text: '' }], indent: 4, tanaFieldValueType: 'options', type: 'p' },
  { id: 'template-field-owner', children: [{ text: '' }], indent: 3, tanaFieldId: 'field-owner', type: 'p' },
  { id: 'template-value-owner', children: [{ text: '' }], indent: 4, tanaFieldValueType: 'from-supertag', type: 'p' },
  {
    id: 'node-project-example',
    children: [
      { text: '示例 ' },
      { children: [{ text: '' }], key: 'supertag-project', type: 'tana_supertag' },
    ],
    indent: 2,
    type: 'p',
  },
  { id: 'field-node-project-summary', children: [{ text: '' }], indent: 3, tanaFieldId: 'field-summary', type: 'p' },
  { id: 'field-value-project-summary', children: [{ text: '' }], indent: 4, tanaFieldValueType: 'plain', type: 'p' },
  { id: 'field-node-project-estimate', children: [{ text: '' }], indent: 3, tanaFieldId: 'field-estimate', type: 'p' },
  { id: 'field-value-project-estimate', children: [{ text: '' }], indent: 4, tanaFieldValueType: 'number', type: 'p' },
  { id: 'field-node-project-active', children: [{ text: '' }], indent: 3, tanaFieldId: 'field-active', type: 'p' },
  { id: 'field-value-project-active', children: [{ text: '' }], indent: 4, tanaFieldValueType: 'checkbox', type: 'p' },
  { id: 'field-node-project-due', children: [{ text: '' }], indent: 3, tanaFieldId: 'field-due', type: 'p' },
  { id: 'field-value-project-due', children: [{ text: '' }], indent: 4, tanaFieldValueType: 'date', type: 'p' },
  { id: 'field-node-project-status', children: [{ text: '' }], indent: 3, tanaFieldId: 'field-status', type: 'p' },
  { id: 'field-value-project-status', children: [{ text: '' }], indent: 4, tanaFieldValueType: 'options', type: 'p' },
  { id: 'field-node-project-owner', children: [{ text: '' }], indent: 3, tanaFieldId: 'field-owner', type: 'p' },
  { id: 'field-value-project-owner', children: [{ text: '' }], indent: 4, tanaFieldValueType: 'from-supertag', type: 'p' },
  { id: 'node-local-persistence', children: [{ text: 'SQLite 在本地持久化文档。' }], indent: 1, type: 'p' },
  {
    id: 'view-projects',
    children: [{ text: '全部项目' }],
    tanaViewDefinition: { clauses: [{ kind: 'has-supertag', supertagId: 'supertag-project' }] },
    type: 'p',
  },
  { id: 'field-summary', children: [{ text: '摘要' }], tanaFieldDefinition: { type: 'plain' }, type: 'p' },
  { id: 'field-estimate', children: [{ text: '预估' }], tanaFieldDefinition: { type: 'number' }, type: 'p' },
  { id: 'field-active', children: [{ text: '进行中' }], tanaFieldDefinition: { type: 'checkbox' }, type: 'p' },
  { id: 'field-due', children: [{ text: '截止日期' }], tanaFieldDefinition: { type: 'date' }, type: 'p' },
  {
    id: 'field-status',
    children: [{ text: '状态' }],
    tanaFieldDefinition: { type: 'options' },
    type: 'p',
  },
  { id: 'option-planned', children: [{ text: '计划中' }], indent: 1, type: 'p' },
  { id: 'option-active', children: [{ text: '进行中' }], indent: 1, type: 'p' },
  { id: 'option-completed', children: [{ text: '已完成' }], indent: 1, type: 'p' },
  {
    id: 'field-owner',
    children: [{ text: '负责人' }],
    tanaFieldDefinition: { sourceSupertagId: 'supertag-project', type: 'from-supertag' },
    type: 'p',
  },
]);
